# Travis-CI Build for bee2
# see travis-ci.org for details

language: c

branches:
  only:
    - master

env:
  global:
    - secure: "NrH9YMK7hLXQD63bj2AHc3aEN8GbaXndTc/SXVL0dVfPa4Z//LQehOcrRkjn7GyX/RPY0pNCYPVEErB6kZ2DJ70KSxdtS9OctkH+oGRqGdnfh2AcaOiVcVZZwIp3ZFd6pzH7jn8nNc4lvZvCjv9UteRZ9jO1YWPvhJNUzwK4RFPFuMYANT9w3IV8pVe2JuUO3qMJWgxrb4yI15Yj+kxkpqRr6mHusaAQpu0dzKGvpbIT+B4dzAtCIvkDRwlmNtqObDiFIoyxJsYtAi8ez3SGAO4+eTKJsIQ1nkK2QrqWf2eRndAdsxAd5t8FlHB40befC95LkJhB4AF0uhnqcyjDTBN7faLuCDOzDfCsWwaLkR2xZADC0WAlBxgrifluOZ3NSKc+ArlAA4gCiJ7ES9r18SuEHW2A2RjZVQ7M4RO1lCrtYSEP9Xy9UjKkgWa7GFE+9nk7QKeonijfeD6n6KvB6lldWK+49kUSuDuYl52aOgm0TexL8ciFYYvWXpJ3lYgKasvdEvA93oHHDpk8cJ+1EvMb12V3hAciAxeIhipeQQnS4pQX2co22IhCIKrGzFzzp42H80jqEtrCu/xlTiI4SEX7kvKjMQaHDkpXzSTuXgg4ydyW/5TIlHqaQDRI4ek9IosAutbW+DQ8CBPrfWpskTDg3XZAcgflglFwbFOVVZ4="

matrix:
  include:
    - os: linux
      env:
        - TRAVIS_DEBIAN_INCREMENT_VERSION_NUMBER="true"
        - TRAVIS_DEBIAN_TARGET_DIR="./release"
      sudo: required
      services:
        - docker
      before_deploy:
        - cd ..
        - sudo apt-get install dpkg-dev
        - wget -O- http://travis.debian.net/script.sh | sh -
      deploy:
        provider: releases
        skip_cleanup: true
        api_key:
          secure: VYuFJ+jEyLLhrCARiDm1lPXX+HcwTcqW9xGXAEC3ZEFjW1lwBweAoe+uteNR56c95J7L42Gy9hRZeA7zipFDsMx3nGF9IfiMjcHUCwpEfVWJ0gkv1zFXltHif0qIEaOBAfABZTJVRxPfCq86AMSocOQO6q9U9HYUXoXk+e7wA6y/Zu8LRspV4tskszw9BWcbrqHDqxmkXjVyMZb1Clz+byWq9LYcstSVi0t2c9z9rDhEKzelm9VW13ybyxs1myoWVsMcb6JJ7oDMunRWqtaTjmn4Inf7enkBjp1UDIy1xeb9f5h0EahVzgS7BKHGml3IZzRWs1SmGT/BNglUuxXbklYKuaiA2q2UhOu9Zyn21iXy26Bc40gpITWYF+zvN9iaBYqrHNIeNvwuOBSoN9fxXDR6bBsToUAzmuNuhCfXko3DvCStju8Gf2lVqU3d5gNWSXaN+h6eIa77XTfMTNUHREO5Gh7EK8rjRQVEhrGYJhWUyCePbmjvydGEyeA6UQEqcidyyjhjP9nF9Xds9rDi3ole/tq0mE/EDoXLehXckMW5u8J8P74QrRLpgyuLWUM72bmm9KOY6fb4BVfpJRf0A6VR40nY0rhuzuwM/dGSfACrZnjQGJMSizTQJ4aGE92pLRBaK2rKZrvXjE+xM07rk+tbFbJMtbxkB+TqdiCYYnc=
        file_glob: true
        file:
         - release/*.deb
         - release/*.tar.xz
         - release/*.dsc
        on:
#          tags: true
          repo: MaryAlex/bee2
          branch: master
    - os: linux
      compiler: gcc
      env:
      - COVERITY_SCAN_PROJECT_NAME="$TRAVIS_REPO_SLUG"
      - COVERITY_SCAN_BRANCH_PATTERN="master"
      - COVERITY_SCAN_BUILD_COMMAND_PREPEND="cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_FAST=ON"
      - COVERITY_SCAN_BUILD_COMMAND="make"
      script:
      - curl -s 'https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh' | bash || true
    - os: linux
      compiler: gcc
      env: BUILD_TYPE="Release" BUILD_FAST="ON"
    - os: osx
      compiler: clang
      env: BUILD_TYPE="Release" BUILD_FAST="OFF"
    - os: linux
      compiler: gcc
      env: BUILD_TYPE="MemSan" BUILD_FAST="ON"
    - os: osx
      compiler: clang
      env: BUILD_TYPE="Check" BUILD_FAST="OFF"
    - os: linux
      compiler: gcc
      env: BUILD_TYPE="Check" BUILD_FAST="ON"
    - os: linux
      compiler: gcc
      sudo: required
      env: BUILD_TYPE="Coverage" BUILD_FAST="OFF"
      install:
      - sudo apt-get install -y lcov
      after_success:
      - lcov -c -i -d src -o coverage_base.info
      - test/testbee2
      - lcov -c -d src -o coverage_test.info
      - lcov -a coverage_base.info -a coverage_test.info -o coverage.info
      - bash <(curl -s https://codecov.io/bash) -f coverage.info

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_FAST=$BUILD_FAST ..
  - make
  - make test
