Document: bee2
Title: Debian bee2 Manual
Author: <insert document author here>
Abstract: This manual describes what bee2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bee2/bee2.sgml.gz

Format: postscript
Files: /usr/share/doc/bee2/bee2.ps.gz

Format: text
Files: /usr/share/doc/bee2/bee2.text.gz

Format: HTML
Index: /usr/share/doc/bee2/html/index.html
Files: /usr/share/doc/bee2/html/*.html
